### ISSUE TITLE
Groups breaking cloud-init

### ISSUE THREAD

**Issue by andrzejwp** [hicknhack-software/ansible-libvirt#7]
Probably due to the same problem described here https://github.com/lxc/lxd/issues/1597 - provisioning a fresh VM with cloud-init doesn't work, when groups are specified like this :

```
# domain/create/defaults/main.yml

groups: 'adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev' # comma separated string!

```

removing whitespace fixes the issue.

Fixed in PR #6

**Comment by arBmind** [comment]
Thx
I merged the PR
